const map=L.map("map",{zoomControl:false,preferCanvas:true}).setView([20,0],2);
L.control.zoom({position:"bottomright"}).addTo(map);
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:"© OpenStreetMap contributors"}).addTo(map);
const S={planes:new Map(),markers:new Map(),trails:new Map(),history:new Map(),airports:[],loaded:false,selected:null,replay:null,replayMarker:null,request:0,busy:false,mode:"global",lastLocalAt:0};
const $=id=>document.getElementById(id),desktop=window.desktopAPI;
const esc=x=>String(x??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const alt=v=>v==null||!Number.isFinite(Number(v))?"-":Math.round(Number(v)).toLocaleString()+" ft";
const spd=v=>v==null||!Number.isFinite(Number(v))?"-":Math.round(Number(v))+" kt";
const num=(v,min,max)=>Number.isFinite(Number(v))&&Number(v)>=min&&Number(v)<=max?Number(v):null;
function normOpenSky(a){const s=a||[];return {hex:String(s[0]||"").trim().toUpperCase(),callsign:String(s[1]||"").trim(),reg:"",type:"",lat:Number(s[6]),lon:Number(s[5]),alt:s[7]==null?null:Number(s[7])*3.28084,gs:s[9]==null?null:Number(s[9])*1.94384,track:s[10],vr:s[11]==null?null:Number(s[11])*196.8504,squawk:String(s[14]||"").trim(),source:"OpenSky"}}
function normAirplanes(a){return {hex:String(a.hex||a.icao||"").trim().toUpperCase(),callsign:String(a.flight||a.callsign||"").trim(),reg:String(a.r||a.registration||"").trim(),type:String(a.t||a.type||a.icao_type||"").trim(),lat:Number(a.lat),lon:Number(a.lon),alt:a.alt_baro??a.alt_geom??a.altitude,gs:a.gs??a.speed,track:a.track??a.heading,vr:a.baro_rate??a.vert_rate,squawk:String(a.squawk||"").trim(),source:"Airplanes.live"}}
function ico(p){const h=Number.isFinite(Number(p.track))?Number(p.track):0;const svg="<svg viewBox='0 0 24 24' width='24' height='24'><path d='M12 1 15 9l6 3v2l-6-1v8l3 2v1H6v-1l3-2v-8l-6 1v-2l6-3z'/></svg>";return L.divIcon({className:"planeMarker",html:"<div class='planeIcon' style='transform:rotate("+h+"deg)'>"+svg+"</div>",iconSize:[24,24],iconAnchor:[12,12]})}
function validQuery(){const lat=num($("lat").value,-90,90),lon=num($("lon").value,-180,180),dist=num($("dist").value,1,250);if(lat===null||lon===null||dist===null)throw Error("Enter a valid latitude, longitude and radius (1–250 NM).");return {lat,lon,dist}}
function setStatus(t,ok){$("status").textContent=t;$("statusDot").style.background=ok?"#43d98c":"#e65f67"}
async function live(){
 if(S.busy)return;S.busy=true;$("refresh").disabled=true;const req=++S.request;$("status").textContent="Updating…";
 try{let ps=[];
  if(S.mode==="global"){const d=desktop?await desktop.global():await fetch("https://opensky-network.org/api/states/all",{cache:"no-store"}).then(r=>{if(!r.ok)throw Error("OpenSky HTTP "+r.status);return r.json()});ps=(d.states||[]).map(normOpenSky)}
  else{const q=validQuery();const d=desktop?await desktop.local(q):await fetch("https://api.airplanes.live/v2/point/"+q.lat+"/"+q.lon+"/"+q.dist,{cache:"no-store"}).then(r=>{if(!r.ok)throw Error("Airplanes.live HTTP "+r.status);return r.json()});ps=(d.ac||d.aircraft||[]).map(normAirplanes)}
  if(req!==S.request)return;render(ps.filter(p=>p.hex&&Number.isFinite(p.lat)&&Number.isFinite(p.lon)&&Math.abs(p.lat)<=90&&Math.abs(p.lon)<=180));setStatus((S.mode==="global"?"GLOBAL":"LOCAL")+" LIVE · "+new Date().toLocaleTimeString(),true)
 }catch(e){if(req===S.request)setStatus("Data error: "+(e.message||"unknown error"),false)}
 finally{if(req===S.request){S.busy=false;$("refresh").disabled=false}}
}
function render(ps){const seen=new Set();ps.forEach(p=>{seen.add(p.hex);S.planes.set(p.hex,p);let m=S.markers.get(p.hex);if(!m){m=S.mode==="global"?L.circleMarker([p.lat,p.lon],{radius:3,stroke:false,fillOpacity:.8,fillColor:"#58b8ff"}):L.marker([p.lat,p.lon],{icon:ico(p)});m.addTo(map);m.on("click",()=>details(p.hex));S.markers.set(p.hex,m)}else{m.setLatLng([p.lat,p.lon]);if(S.mode==="local"&&m.setIcon)m.setIcon(ico(p))}
 const h=S.history.get(p.hex)||[],last=h[h.length-1],moved=!last||Math.abs(last.lat-p.lat)>.00001||Math.abs(last.lon-p.lon)>.00001||last.alt!==p.alt;if(moved){h.push({t:Date.now(),lat:p.lat,lon:p.lon,alt:p.alt,track:p.track});if(h.length>600)h.shift();S.history.set(p.hex,h)}
 if(h.length>1){let line=S.trails.get(p.hex);if(!line){line=L.polyline(h.map(x=>[x.lat,x.lon]),{color:"#42a5ff",weight:2,opacity:.45}).addTo(map);S.trails.set(p.hex,line)}else line.setLatLngs(h.map(x=>[x.lat,x.lon]))}});
 S.markers.forEach((m,h)=>{if(!seen.has(h)){map.removeLayer(m);S.markers.delete(h);S.planes.delete(h);const line=S.trails.get(h);if(line){map.removeLayer(line);S.trails.delete(h)}}});list();$("count").textContent=ps.length+" aircraft"}
function list(){const q=$("search").value.trim().toLowerCase();const a=[...S.planes.values()].filter(p=>(p.callsign+" "+p.reg+" "+p.type+" "+p.hex).toLowerCase().includes(q)).sort((x,y)=>(Number(y.alt)||0)-(Number(x.alt)||0));$("list").innerHTML=a.slice(0,500).map(p=>"<div class='card' data-hex='"+esc(p.hex)+"'><div class='row'><b>"+esc(p.callsign||p.reg||p.hex)+"</b><span class='pill'>"+esc(p.type||p.source||"-")+"</span></div><div class='row muted'><span>"+esc(p.reg||p.hex)+"</span><span>"+alt(p.alt)+" · "+spd(p.gs)+"</span></div></div>").join("")||"<div class='card muted'>No aircraft match.</div>";document.querySelectorAll(".card[data-hex]").forEach(e=>e.onclick=()=>details(e.dataset.hex))}
async function details(hex){const p=S.planes.get(hex);if(!p)return;S.selected=hex;$("details").classList.remove("hidden");$("detailContent").innerHTML="<h2>"+esc(p.callsign||"Unknown flight")+"</h2><div class='muted'>"+esc(p.reg)+" · "+esc(p.type||"Unknown type")+" · "+esc(p.hex)+"</div><div id='photoBox'></div><div class='route' id='routeBox'><span>Route</span><strong>Loading…</strong></div><div class='detailGrid'><div class='stat'><small>Altitude</small><b>"+alt(p.alt)+"</b></div><div class='stat'><small>Ground speed</small><b>"+spd(p.gs)+"</b></div><div class='stat'><small>Track</small><b>"+(Number.isFinite(Number(p.track))?Math.round(Number(p.track)):"-")+"°</b></div><div class='stat'><small>Vertical rate</small><b>"+(p.vr??"-")+" fpm</b></div><div class='stat'><small>Squawk</small><b>"+esc(p.squawk||"-")+"</b></div><div class='stat'><small>Position</small><b>"+p.lat.toFixed(4)+", "+p.lon.toFixed(4)+"</b></div></div><p class='muted'>Session points: "+(S.history.get(hex)||[]).length+"</p>";
 try{const d=desktop?await desktop.aircraft(p.hex,p.callsign):await fetch("https://api.adsbdb.com/v0/aircraft/"+encodeURIComponent(p.hex)+"?callsign="+encodeURIComponent(p.callsign||"")).then(r=>r.ok?r.json():null);if(S.selected!==hex)return;const ac=d?.response?.aircraft;if(ac?.url_photo_thumbnail)$("photoBox").innerHTML="<img class='hero' src='"+esc(ac.url_photo||ac.url_photo_thumbnail)+"' alt='Aircraft photo' referrerpolicy='no-referrer'><div class='muted'>Photo: Planespotters.net</div>";const rt=d?.response?.flightroute,box=$("routeBox");if(rt)box.innerHTML="<span>"+esc(rt.origin?.iata_code||rt.origin?.icao_code||"?")+"</span><strong>→</strong><span>"+esc(rt.destination?.iata_code||rt.destination?.icao_code||"?")+"</span>";else box.innerHTML="<span>Route unavailable</span>"}catch{const box=$("routeBox");if(box)box.innerHTML="<span>Metadata unavailable</span>"}}
async function airports(){if(S.loaded)return;try{const r=await fetch("https://davidmegginson.github.io/ourairports-data/airports.csv",{cache:"no-store"});if(!r.ok)throw Error();S.airports=parseCSV(await r.text());S.loaded=true}catch{$("airportResults").innerHTML="<div class='airportResult'>Airport database unavailable.</div>"}}
function parseCSV(t){const lines=t.split(/\r?\n/);if(!lines.length)return[];const h=lines[0].split(",").map(x=>x.replace(/^"|"$/g,""));return lines.slice(1).map(line=>{let v=[],c="",q=false;for(let i=0;i<line.length;i++){const x=line[i];if(x==='"'){if(q&&line[i+1]==='"'){c+='"';i++}else q=!q}else if(x===","&&!q){v.push(c);c=""}else c+=x}v.push(c);const o={};h.forEach((k,i)=>o[k]=v[i]||"");return o}).filter(x=>x.ident&&Number.isFinite(Number(x.latitude_deg))&&Number.isFinite(Number(x.longitude_deg)))}
function airportResults(){const q=$("airportSearch").value.trim().toLowerCase();if(!q){$("airportResults").innerHTML="";return}const a=S.airports.filter(x=>(x.ident+" "+x.iata_code+" "+x.name+" "+x.municipality).toLowerCase().includes(q)).slice(0,30);$("airportResults").innerHTML=a.map(x=>"<div class='airportResult' data-icao='"+esc(x.ident)+"' data-lat='"+esc(x.latitude_deg)+"' data-lon='"+esc(x.longitude_deg)+"'><b>"+esc(x.ident)+"</b> · "+esc(x.iata_code||"-")+"<br><span class='muted'>"+esc(x.name)+" · "+esc(x.municipality||"")+"</span></div>").join("")||"<div class='airportResult'>No airports found.</div>";document.querySelectorAll(".airportResult[data-lat]").forEach(e=>e.onclick=()=>selectAirport(e.dataset.icao,e.dataset.lat,e.dataset.lon))}
async function selectAirport(icao,lat,lon){$("lat").value=Number(lat).toFixed(4);$("lon").value=Number(lon).toFixed(4);$("dist").value="25";map.setView([lat,lon],10);$("airportTraffic").innerHTML="<b>"+esc(icao)+"</b> traffic area · loading…";S.mode="local";activateMode();await live();$("airportTraffic").innerHTML="<b>"+esc(icao)+"</b> · "+S.planes.size+" aircraft within 25 NM<br><span class='muted'>Live traffic, not scheduled airline data.</span>"}
function activateMode(){S.markers.forEach(m=>map.removeLayer(m));S.markers.clear();S.trails.forEach(m=>map.removeLayer(m));S.trails.clear();$("globalBtn").classList.toggle("active",S.mode==="global");$("localBtn").classList.toggle("active",S.mode==="local")}
async function loadReplay(){const hex=($("replayHex").value||S.selected||"").trim().toLowerCase(),date=$("replayDate").value;if(!/^[0-9a-f]{6}$/.test(hex)||!date){$("replayMessage").textContent="Enter a 6-character ICAO hex and a date.";return}$("replayMessage").textContent="Loading historical trace…";try{const d=desktop?await desktop.history(hex,date):await fetch("https://globe.airplanes.live/globe_history/"+date.slice(0,4)+"/"+date.slice(5,7)+"/"+date.slice(8,10)+"/traces/"+hex.slice(-2)+"/trace_full_"+hex+".json").then(r=>{if(!r.ok)throw Error("HTTP "+r.status);return r.json()});const trace=Array.isArray(d?.trace)?d.trace:[];if(!trace.length)throw Error("No historical data for that date");const base=Number(d.timestamp||d.start||Date.parse(date)/1000);S.replay=trace.map(x=>({t:(base+Number(x[0]||0))*1000,lat:Number(x[1]),lon:Number(x[2]),alt:typeof x[3]==="number"?x[3]:null,track:x[4]})).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon));$("replaySlider").disabled=false;$("replaySlider").max=Math.max(0,S.replay.length-1);$("replaySlider").value=0;$("replayMessage").textContent=S.replay.length+" historical points loaded.";drawReplay()}catch(e){S.replay=null;$("replaySlider").disabled=true;$("replayMessage").textContent="Replay unavailable: "+e.message}}
function drawReplay(){const x=S.replay?.[Number($("replaySlider").value)];if(!x)return;map.setView([x.lat,x.lon],Math.max(map.getZoom(),7));$("replayTime").textContent=new Date(x.t).toLocaleString()+" · "+alt(x.alt);if(S.replayMarker)S.replayMarker.setLatLng([x.lat,x.lon]).setIcon(ico(x));else S.replayMarker=L.marker([x.lat,x.lon],{icon:ico(x)}).addTo(map)}
$("globalBtn").onclick=()=>{S.mode="global";activateMode();map.setView([20,0],2);live()};$("localBtn").onclick=()=>{S.mode="local";activateMode();live()};$("refresh").onclick=live;$("search").oninput=list;$("closeDetails").onclick=()=>{$("details").classList.add("hidden");S.selected=null};$("replayBtn").onclick=()=>{$("replay").classList.remove("hidden");$("replayHex").value=S.selected||"";$("replayDate").value=new Date().toISOString().slice(0,10)};$("loadReplay").onclick=loadReplay;$("replaySlider").oninput=drawReplay;$("clearReplay").onclick=()=>{$("replay").classList.add("hidden");S.replay=null;$("replaySlider").disabled=true;if(S.replayMarker){map.removeLayer(S.replayMarker);S.replayMarker=null}};
$("airportsBtn").onclick=async()=>{$("airportPanel").classList.toggle("hidden");if(!$("airportPanel").classList.contains("hidden")){await airports();$("airportSearch").focus()}};$("airportSearch").oninput=airportResults;
$("locBtn").onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{$("lat").value=p.coords.latitude.toFixed(4);$("lon").value=p.coords.longitude.toFixed(4);map.setView([p.coords.latitude,p.coords.longitude],7);S.mode="local";activateMode();live()},()=>setStatus("Location permission unavailable",false));
let nextTick=0;function schedule(){const delay=S.mode==="global"?300000:10000;clearTimeout(nextTick);nextTick=setTimeout(()=>{if(!S.busy)live();schedule()},delay)}map.on("moveend",()=>{if(S.mode==="local"&&!S.busy)live()});schedule();
window.addEventListener("error",e=>setStatus("UI error: "+e.message,false));window.addEventListener("unhandledrejection",()=>setStatus("Background error",false));
activateMode();live();