const map=L.map("map",{zoomControl:false}).setView([36.8065,10.1815],5);L.control.zoom({position:"bottomright"}).addTo(map);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:"© OpenStreetMap contributors"}).addTo(map);
const S={planes:new Map(),markers:new Map(),trails:new Map(),history:new Map(),airports:[],loaded:false,selected:null,replay:null,replayMarker:null};const $=id=>document.getElementById(id);const desktop=window.desktopAPI;
const alt=v=>v==null?"-":Math.round(Number(v)).toLocaleString()+" ft",spd=v=>v==null?"-":Math.round(Number(v))+" kt";
function norm(a){return{hex:(a.hex||a.icao||"").toUpperCase(),callsign:(a.flight||a.callsign||"").trim(),reg:a.r||a.registration||"",type:a.t||a.type||a.icao_type||"",lat:Number(a.lat),lon:Number(a.lon),alt:a.alt_baro??a.alt_geom??a.altitude,gs:a.gs??a.speed,track:a.track??a.heading,vr:a.baro_rate??a.vert_rate,squawk:a.squawk}}
function ico(p){return L.divIcon({className:"",html:"<div class='planeIcon' style='transform:rotate("+((Number(p.track)||0))+"deg)'>✈</div>",iconSize:[24,24],iconAnchor:[12,12]})}
async function live(){const lat=Number($("lat").value),lon=Number($("lon").value),dist=Number($("dist").value);$("status").textContent="Updating...";try{let d;if(desktop)d=await desktop.nearby({lat,lon,dist});else{const r=await fetch("https://api.adsb.lol/v2/lat/"+lat+"/lon/"+lon+"/dist/"+dist);if(!r.ok)throw Error("HTTP "+r.status);d=await r.json()}render((d.aircraft||[]).map(norm).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)));$("status").textContent="LIVE · "+new Date().toLocaleTimeString();$("statusDot").style.background="#43d98c"}catch(e){$("status").textContent="Data error: "+e.message;$("statusDot").style.background="#e65f67"}}
function render(ps){const seen=new Set();ps.forEach(p=>{seen.add(p.hex);S.planes.set(p.hex,p);let m=S.markers.get(p.hex);if(!m){m=L.marker([p.lat,p.lon],{icon:ico(p)}).addTo(map);m.on("click",()=>details(p.hex));S.markers.set(p.hex,m)}else{m.setLatLng([p.lat,p.lon]);m.setIcon(ico(p))}let h=S.history.get(p.hex)||[];h.push({t:Date.now(),lat:p.lat,lon:p.lon,alt:p.alt});if(h.length>300)h.shift();S.history.set(p.hex,h);if(h.length>1){let line=S.trails.get(p.hex);if(!line){line=L.polyline(h.map(x=>[x.lat,x.lon]),{color:"#42a5ff",weight:2,opacity:.45}).addTo(map);S.trails.set(p.hex,line)}else line.setLatLngs(h.map(x=>[x.lat,x.lon]))}});S.markers.forEach((m,h)=>{if(!seen.has(h)){map.removeLayer(m);S.markers.delete(h);S.planes.delete(h)}});list();$("count").textContent=ps.length+" aircraft"}
function list(){const q=$("search").value.toLowerCase();const a=[...S.planes.values()].filter(p=>(p.callsign+" "+p.reg+" "+p.type+" "+p.hex).toLowerCase().includes(q)).sort((x,y)=>(Number(y.alt)||0)-(Number(x.alt)||0));$("list").innerHTML=a.map(p=>"<div class='card' data-hex='"+p.hex+"'><div class='row'><b>"+(p.callsign||p.reg||p.hex)+"</b><span class='pill'>"+(p.type||"-")+"</span></div><div class='row muted'><span>"+(p.reg||p.hex)+"</span><span>"+alt(p.alt)+" · "+spd(p.gs)+"</span></div></div>").join("")||"<div class='card muted'>No aircraft match.</div>";document.querySelectorAll(".card[data-hex]").forEach(e=>e.onclick=()=>details(e.dataset.hex))}
async function details(hex){const p=S.planes.get(hex);if(!p)return;S.selected=hex;$("details").classList.remove("hidden");$("detailContent").innerHTML="<h2>"+(p.callsign||"Unknown flight")+"</h2><div class='muted'>"+(p.reg||"")+" · "+(p.type||"Unknown type")+" · "+p.hex+"</div><div id='photoBox'></div><div class='route' id='routeBox'><span>Route</span><strong>Loading...</strong></div><div class='detailGrid'><div class='stat'><small>Altitude</small><b>"+alt(p.alt)+"</b></div><div class='stat'><small>Ground speed</small><b>"+spd(p.gs)+"</b></div><div class='stat'><small>Track</small><b>"+(p.track??"-")+"°</b></div><div class='stat'><small>Vertical rate</small><b>"+(p.vr??"-")+" fpm</b></div><div class='stat'><small>Squawk</small><b>"+(p.squawk||"-")+"</b></div><div class='stat'><small>Position</small><b>"+p.lat.toFixed(4)+", "+p.lon.toFixed(4)+"</b></div></div><p class='muted'>Session track points: "+(S.history.get(hex)||[]).length+"</p>";try{let d=desktop?await desktop.aircraft(p.reg||p.hex):await fetch("https://api.adsbdb.com/v0/aircraft/"+encodeURIComponent(p.reg||p.hex)).then(r=>r.ok?r.json():null);let ac=d&&d.response&&d.response.aircraft;if(ac&&ac.url_photo_thumbnail)$("photoBox").innerHTML="<img class='hero' src='"+(ac.url_photo||ac.url_photo_thumbnail)+"'><div class='muted'>Photo: Planespotters.net</div>";let r=desktop?await desktop.route(p.callsign):await fetch("https://api.adsbdb.com/v0/callsign/"+encodeURIComponent(p.callsign)).then(x=>x.ok?x.json():null);let rt=r&&r.response&&r.response.flightroute;if(rt)$("routeBox").innerHTML="<span>"+((rt.origin&&(rt.origin.iata_code||rt.origin.icao_code))||"?")+"</span><strong>→</strong><span>"+((rt.destination&&(rt.destination.iata_code||rt.destination.icao_code))||"?")+"</span>"}catch{}}
async function airports(){if(S.loaded)return;try{const t=await fetch("https://davidmegginson.github.io/ourairports-data/airports.csv").then(r=>r.text());S.airports=parseCSV(t);S.loaded=true}catch{$("airportResults").innerHTML="<div class='airportResult'>Airport database unavailable.</div>"}}
function parseCSV(t){const lines=t.split(/\r?\n/),h=lines[0].split(",").map(x=>x.replace(/^"|"$/g,""));return lines.slice(1).map(line=>{let v=[],c="",q=false;for(let i=0;i<line.length;i++){let x=line[i];if(x==='"'){if(q&&line[i+1]==='"'){c+='"';i++}else q=!q}else if(x===","&&!q){v.push(c);c=""}else c+=x}v.push(c);let o={};h.forEach((k,i)=>o[k]=v[i]||"");return o}).filter(x=>x.ident&&x.latitude_deg&&x.longitude_deg)}
function airportResults(){const q=$("airportSearch").value.toLowerCase();const a=S.airports.filter(x=>(x.ident+" "+x.iata_code+" "+x.name+" "+x.municipality).toLowerCase().includes(q)).slice(0,30);$("airportResults").innerHTML=a.map(x=>"<div class='airportResult' data-lat='"+x.latitude_deg+"' data-lon='"+x.longitude_deg+"'><b>"+x.ident+"</b> · "+(x.iata_code||"-")+"<br><span class='muted'>"+x.name+" · "+(x.municipality||"")+"</span></div>").join("");document.querySelectorAll(".airportResult[data-lat]").forEach(e=>e.onclick=()=>selectAirport(e.dataset.lat,e.dataset.lon))}
function selectAirport(lat,lon){$("lat").value=Number(lat).toFixed(4);$("lon").value=Number(lon).toFixed(4);map.setView([lat,lon],9);live()}
function replay(){const h=S.history.get(S.selected)||[];if(h.length<2){alert("Select an aircraft and let the tracker collect a few points first.");return}S.replay=h;$("replay").classList.remove("hidden");$("replaySlider").max=h.length-1;$("replaySlider").value=0;drawReplay()}
function drawReplay(){const x=S.replay&&S.replay[Number($("replaySlider").value)];if(!x)return;map.setView([x.lat,x.lon],map.getZoom());$("replayTime").textContent=new Date(x.t).toLocaleTimeString()+" · "+alt(x.alt);if(S.replayMarker)S.replayMarker.setLatLng([x.lat,x.lon]);else S.replayMarker=L.marker([x.lat,x.lon],{icon:ico({track:0})}).addTo(map)}
$("refresh").onclick=live;$("search").oninput=list;$("closeDetails").onclick=()=>$("details").classList.add("hidden");$("replayBtn").onclick=replay;$("replaySlider").oninput=drawReplay;$("clearReplay").onclick=()=>{$("replay").classList.add("hidden");if(S.replayMarker){map.removeLayer(S.replayMarker);S.replayMarker=null}};$("airportsBtn").onclick=async()=>{$("airportPanel").classList.toggle("hidden");await airports()};$("airportSearch").oninput=airportResults;$("locBtn").onclick=()=>navigator.geolocation&&navigator.geolocation.getCurrentPosition(p=>{$("lat").value=p.coords.latitude.toFixed(4);$("lon").value=p.coords.longitude.toFixed(4);map.setView([p.coords.latitude,p.coords.longitude],7);live()});setInterval(live,15000);live();