const {app,BrowserWindow,ipcMain}=require("electron");
const path=require("path"),https=require("https");
const MAX_RADIUS=250,MAX_BYTES=12*1024*1024;
function get(url){return new Promise((resolve,reject)=>{const req=https.get(url,{headers:{"User-Agent":"ADS-B-Flight-Tracker/1.0","Accept":"application/json"}},r=>{if(r.statusCode<200||r.statusCode>=300){r.resume();return reject(new Error("HTTP "+r.statusCode))}let d="",size=0;r.setEncoding("utf8");r.on("data",c=>{size+=Buffer.byteLength(c);if(size>MAX_BYTES){req.destroy(new Error("Response too large"));return}d+=c});r.on("end",()=>{try{resolve(JSON.parse(d))}catch(e){reject(new Error("Invalid JSON response"))}});r.on("error",reject)});req.on("error",reject);req.setTimeout(12000,()=>req.destroy(new Error("Request timeout")))});}
ipcMain.handle("adsb:nearby",async(_,q)=>{const lat=Number(q?.lat),lon=Number(q?.lon),dist=Number(q?.dist);if(!Number.isFinite(lat)||lat<-90||lat>90||!Number.isFinite(lon)||lon<-180||lon>180||!Number.isFinite(dist)||dist<1||dist>MAX_RADIUS)throw new Error("Invalid map query");return get("https://api.adsb.lol/v2/lat/"+lat+"/lon/"+lon+"/dist/"+dist)});
ipcMain.handle("route:lookup",async(_,c)=>{const v=String(c||"").trim();if(!v||v.length>32)return null;try{return await get("https://api.adsbdb.com/v0/callsign/"+encodeURIComponent(v))}catch{return null}});
ipcMain.handle("aircraft:lookup",async(_,q)=>{const id=String(q?.id||"").trim(),callsign=String(q?.callsign||"").trim();if(!id||id.length>32||callsign.length>32)return null;try{let u="https://api.adsbdb.com/v0/aircraft/"+encodeURIComponent(id);if(callsign)u+="?callsign="+encodeURIComponent(callsign);return await get(u)}catch{return null}});
function createWindow(){const w=new BrowserWindow({width:1500,height:900,minWidth:1050,minHeight:650,show:false,backgroundColor:"#07111d",webPreferences:{preload:path.join(__dirname,"preload.cjs"),contextIsolation:true,nodeIntegration:false,sandbox:true}});w.once("ready-to-show",()=>w.show());w.webContents.on("render-process-gone",(_,d)=>console.error("Renderer exited:",d.reason));w.loadFile(path.join(__dirname,"..","index.html"))}
app.whenReady().then(()=>{createWindow();app.on("activate",()=>{if(BrowserWindow.getAllWindows().length===0)createWindow()})});
app.on("window-all-closed",()=>{if(process.platform!=="darwin")app.quit()});